steps:
#    - label: "Configure AWS credentials"
#      key: aws-login
#
#    - wait

#    - label: "generate linux tarball"
#      command:
#        - make install
#        - npm cache clear & npm install
#        - npm install -g @oclif/dev-cli
#        - oclif-dev pack -t linux-x64,linux-arm
#      plugins:
#        - docker#v3.8.0:
#            image: "node:14"

#    - wait

    - label: "Build Deb Package"
      key: gpg
      command:
        - make install
        - npm cache clear & npm install
        - node .buildkite/pack-debian-apt.js x64,arm
      plugins:
        - docker#v3.8.0:
            image: "registry.twilio.com/twilio/cookbook-buildkite-environment/role:0.1.3"
            propagate-aws-auth-tokens: true

#notify:
#  - slack: "#general"
#    if: build.state == "failed" || build.state == "canceled"
#    message: "APT Release Failed"

