agents:
  queue: "devtools-buildkite-agent"
steps:
    - label: "Configure AWS credentials"
      key: aws-login

    - wait

    - label: "generate linux tarball"
      command:
        - npm cache clear & npm install
        - npm install -g @oclif/dev-cli
        - oclif-dev pack -t linux-x64,linux-arm

    - wait

    - label: "Build Deb Package"
      key: gpg
      command: node .buildkite/pack-debian-apt.js x64,arm

notify:
  - slack: "#general"
    if: build.state == "failed" || build.state == "canceled"
    message: "APT Release Failed"

