steps:
#    - label: "Configure AWS credentials"
#      key: aws-login
#
#    - wait

#    - label: "generate linux tarball"
#      command:
#        - make install
#        - npm cache clear & npm install
#        - npm install -g @oclif/dev-cli
#        - oclif-dev pack -t linux-x64,linux-arm
#      plugins:
#        - docker#v3.8.0:
#            image: "node:14"

#    - wait

#    - label: "Aws credentials"
#      command:
#        - aws s3 cp
#      plugins:
#        - docker#v3.11.0:
#            propagate-environment: true
#            image: "amazon/aws-cli:2.0.6"
#            entrypoint: ""
#            shell: [ "/bin/sh", "-e", "-c" ]
#
#    - wait

    - label: "Build Deb Package"
      key: gpg
      command:
        - make install
        - npm cache clear & npm install
        - node . ./.github/scripts/pack-debian-apt.js x64,arm
      plugins:
        - docker#v3.8.0:
            image: "node:14"

#notify:
#  - slack: "#general"
#    if: build.state == "failed" || build.state == "canceled"
#    message: "APT Release Failed"

