#!/bin/bash

#set -euo pipefail

if [ "$BUILDKITE_STEP_KEY" == "aws-login" ]
then
    echo '--- :buildkite: Getting Secrets from Admiral'

    apk add --no-cache aws-cli
    aws s3 cp s3://com-twilio-corp-us1-secrets/v1/buildkite-build-worker/jobs_dev_interfaces_aws_gpg_s3/AWS_ACCESS_KEY_ID aws_access_key_id
    AWS_ACCESS_KEY_ID=$(cat aws_access_key_id)
    rm aws_access_key_id

    export AWS_ACCESS_KEY_ID

    apk add --no-cache aws-cli
    aws s3 cp s3://com-twilio-corp-us1-secrets/v1/buildkite-build-worker/jobs_dev_interfaces_aws_gpg_s3/AWS_SECRET_ACCESS_KEY aws_secret_access_key
    AWS_SECRET_ACCESS_KEY=$(cat aws_secret_access_key)
    rm aws_secret_access_key

    export AWS_SECRET_ACCESS_KEY

    apk add --no-cache aws-cli
    aws s3 cp s3://com-twilio-corp-us1-secrets/v1/buildkite-build-worker/jobs_dev_interfaces_aws_gpg_s3/AWS_SESSION_TOKEN aws_session_token
    AWS_SESSION_TOKEN=$(cat aws_session_token)
    rm aws_session_token

    export AWS_SESSION_TOKEN
fi
