name: Upload Release assets
on: [workflow_dispatch]
jobs:
  upload-assets:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload binaries to release - tar.xz
        if: always()
        run: |
          node .github/scripts/update-platform-executables.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE: ./darwin-arm64
          ASSET_NAME: darwin-arm64
          OVERWRITE: true
          TAG_NAME: ${{github.event.inputs.tag-name}}
          REPO_NAME: ${{ github.repository }}
